#!/bin/sh

ESHOST="${ESHOST:-localhost}"

usage() {
  echo "" >&2
  echo "Usage: $0 [ -s N | -h ] " >&2
  echo "" >&2
  echo "return health status on cluster host: $ESHOST" >&2
  echo "" >&2
  echo "-s : keep polling status every N seconds" >&2
  echo "-h : print this usage" >&2
  echo "" >&2
  exit 1
}

LOOP=0
while getopts "s:?" o; do
    case "${o}" in
        s)
            shift
            if [ "${1:-xx}" == "xx" ]; then
              LOOP=60
            else
              LOOP=${1}
            fi
            ;;
        *|h|?)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

ESHOST="${ESHOST:-localhost}"
while true; do
  curl -knsX GET "https://$ESHOST:9200/_cluster/health?pretty"
  if [ $LOOP -gt 0 ]; then
    sleep $LOOP
  else
    break
  fi
done